#ifndef MENU_H
#define MENU_H

enum {
        MENU_EDIT_UNDO,
	MENU_EDIT_COPY,
	MENU_EDIT_CUT,
	MENU_EDIT_PASTE,
	MENU_VIEW_FONT,
	MENU_RUN_SELECTION,
        MENU_RUN_LINE,
        MENU_RUN_BREAK,
        MENU_RUN_ENTER,
	MENU_RUN_CTRL_ENTER,
        MENU_PICO_RESET,
	MENU_HELP_ABOUT
};

#endif
